#!/usr/bin/env sh

# Gera ou atualiza o changelog
npx conventional-changelog -n ./changelog.config.js -i CHANGELOG.md -s -r 0

# Adiciona o changelog atualizado ao índice
git add CHANGELOG.md

# Verifica se há mudanças no changelog e faz o commit com uma mensagem específica
if ! git diff --cached --quiet; then
  git commit -m ":memo: docs: update changelog"
fi