name: Lighthouse Audit
on:
  workflow_run:
    workflows: ['Deploy to Vercel']
    types:
      - completed
  workflow_dispatch:
jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://portal-ascepa.vercel.app/
          configPath: './.github/lighthouse/lighthouserc.json'
          temporaryPublicStorage: true
